<?php
/** @var \Cochez\RequestQuote\Block\Quote\Sidebar $block  */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
?>

<div data-block="miniquote" class="minicart-wrapper">
    <a class="action showquote" href="<?= $block->escapeUrl($block->getShoppingQuoteUrl()) ?>"
       data-bind="scope: 'miniquote_content'">
        <span class="text"><?= $block->escapeHtml(__('My Quote')) ?></span>
        <span class="counter qty empty"
              data-bind="css: { empty: !!getQuoteParam('summary_count') == false && !isLoading() },
               blockLoader: isLoading">
            <span class="counter-number">
                <!-- ko if: getQuoteParam('summary_count') -->
                <!-- ko text: getQuoteParam('summary_count').toLocaleString(window.LOCALE) --><!-- /ko -->
                <!-- /ko -->
            </span>
            <span class="counter-label">
            <!-- ko if: getQuoteParam('summary_count') -->
                <!-- ko text: getQuoteParam('summary_count').toLocaleString(window.LOCALE) --><!-- /ko -->
                <!-- ko i18n: 'items' --><!-- /ko -->
                <!-- /ko -->
            </span>
        </span>
    </a>
    <?php if ($block->getIsNeedToDisplaySideBar()):?>
        <div class="block block-miniquote"
             data-role="dropdownDialog"
             data-mage-init='{"dropdownDialog":{
                "appendTo":"[data-block=miniquote]",
                "triggerTarget":".showquote",
                "timeout": "2000",
                "closeOnMouseLeave": false,
                "closeOnEscape": true,
                "triggerClass":"active",
                "parentClass":"active",
                "buttons":[]}}'>
            <div id="miniquote-content-wrapper" data-bind="scope: 'miniquote_content'">
                <!-- ko template: getTemplate() --><!-- /ko -->
            </div>
            <?= $block->getChildHtml('miniquote.addons') ?>
        </div>
    <?php else: ?>
        <?php $scriptString = <<<script
            require(['jquery'], function ($) {
                $('a.action.showquote').on('click', function() {
                    $(document.body).trigger('processStart');
                });
            });
script;
        ?>
        <?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false); ?>
    <?php endif ?>
    <?= /* @noEscape */ $secureRenderer->renderTag('script', [], 'window.checkout = ' .
        /* @noEscape */ $block->getSerializedConfig(), false); ?>
    <script type="text/x-magento-init">
        {
            "[data-block='miniquote']": {
                "Magento_Ui/js/core/app": <?= /* @noEscape */ $block->getJsLayout() ?>
        },
        "*": {
            "Magento_Ui/js/block-loader": "<?= $block->escapeJs(
            $block->escapeUrl($block->getViewFileUrl('images/loader-1.gif'))
        ) ?>"
        }
    }
    </script>
</div>
